# Generated by Django 4.2.4 on 2024-03-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('standard', 'name'), 'verbose_name': 'Нормативный документ', 'verbose_name_plural': 'Нормативные документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='standard',
            field=models.CharField(default='gost', max_length=32, verbose_name='Нормативный документ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
    ]
