version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - 8000:80