# Generated by Django 4.2.4 on 2023-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_invitation_options_alter_invitation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='laboratory_staff',
            field=models.BooleanField(default=False, help_text='Указывает, что пользователь является администратором лаборатории', verbose_name='Администратор лаборатории'),
        ),
    ]
