# Generated by Django 4.2.4 on 2023-08-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invitation_email_alter_user_laboratory_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='laboratory_staff',
        ),
    ]
