# Generated by Django 4.2.4 on 2023-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название реактива'),
        ),
    ]
