# Generated by Django 4.2.4 on 2023-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_alter_reagent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название реактива'),
        ),
    ]
