# Generated by Django 4.2.4 on 2023-08-23 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название лаборатории')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_admin', to=settings.AUTH_USER_MODEL, verbose_name='Администратор лаборатории')),
            ],
        ),
    ]
