# Generated by Django 4.2.4 on 2023-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='description',
            field=models.TextField(default='Описание лаборатории', verbose_name='Описание'),
        ),
    ]
