# Generated by Django 4.2.4 on 2024-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_document_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='standard',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Нормативный документ'),
        ),
    ]
