# Generated by Django 4.2.4 on 2024-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='name', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
