# Generated by Django 4.2.4 on 2024-04-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-standard', 'name'), 'verbose_name': 'Нормативный документ', 'verbose_name_plural': 'Нормативные документы'},
        ),
    ]
