# Generated by Django 4.2.4 on 2023-08-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True, verbose_name='Индекс')),
                ('name', models.CharField(max_length=200, verbose_name='Название реактива')),
                ('grade', models.CharField(choices=[('тех.', 'Технический'), ('ч.', 'Чистый'), ('ч.д.а.', 'Чистый для анализа'), ('х.ч.', 'Химически чистый'), ('сп.ч.', 'Спектрально чистый'), ('осч', 'Особо чистый')], max_length=10, null=True, verbose_name='Марка')),
                ('expiration_date', models.DateField(verbose_name='Годен до')),
            ],
        ),
    ]
