# Generated by Django 4.2.4 on 2023-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Масса, г'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='manufacture_date',
            field=models.DateField(null=True, verbose_name='Дата производства'),
        ),
    ]
