# Generated by Django 4.2.4 on 2023-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reagent',
            options={'ordering': ('index',), 'verbose_name': 'Реагент', 'verbose_name_plural': 'Реагенты'},
        ),
        migrations.AlterField(
            model_name='reagent',
            name='grade',
            field=models.CharField(blank=True, choices=[('тех.', 'Технический'), ('ч.', 'Чистый'), ('ч.д.а.', 'Чистый для анализа'), ('х.ч.', 'Химически чистый'), ('сп.ч.', 'Спектрально чистый'), ('осч', 'Особо чистый')], max_length=10, verbose_name='Марка'),
        ),
    ]
