# Generated by Django 4.2.4 on 2023-08-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_reagent_amount_reagent_manufacture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество, г'),
        ),
    ]
