# Generated by Django 4.2.4 on 2023-08-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_alter_reagent_options_alter_reagent_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название реактива')),
            ],
            options={
                'verbose_name': 'Название реактива',
                'verbose_name_plural': 'Названия реактивов',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='reagent',
            options={'ordering': ('index',), 'verbose_name': 'Реактив', 'verbose_name_plural': 'Реактивы'},
        ),
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.reagentname', verbose_name='Название реактива'),
        ),
    ]
