# Generated by Django 4.2.4 on 2023-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0003_alter_reagent_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество, г'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Годен до'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='grade',
            field=models.CharField(blank=True, choices=[('тех.', 'Технический'), ('ч.', 'Чистый'), ('ч.д.а.', 'Чистый для анализа'), ('х.ч.', 'Химически чистый'), ('сп.ч.', 'Спектрально чистый'), ('осч', 'Особо чистый')], max_length=10, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
    ]
