# Generated by Django 4.2.4 on 2023-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0004_alter_reagentname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='index',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Индекс'),
        ),
    ]
