# Generated by Django 4.2.4 on 2023-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0005_alter_reagent_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название реактива'),
        ),
        migrations.DeleteModel(
            name='ReagentName',
        ),
    ]
