# Generated by Django 4.2.4 on 2023-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0006_alter_reagent_name_delete_reagentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Годен до'),
        ),
    ]
