# Generated by Django 4.2.4 on 2023-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0007_alter_reagent_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='grade',
            field=models.CharField(choices=[('тех.', 'Технический'), ('ч.', 'Чистый'), ('ч.д.а.', 'Чистый для анализа'), ('х.ч.', 'Химически чистый'), ('сп.ч.', 'Спектрально чистый'), ('осч', 'Особо чистый')], max_length=10, null=True, verbose_name='Марка'),
        ),
    ]
